services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DB:-app_db}'
    ports:
      - '5432:5432'
    networks:
      - backend

  backend:
    build: ./backend
    container_name: backend
    environment:
      DATABASE_URL: '${DATABASE_URL:-postgresql://user:password@db:5432/app_db}'
      SECRET_KEY: '${SECRET_KEY:-your_secret_key}'
      ALGORITHM: '${ALGORITHM:-HS256}'
      ACCESS_TOKEN_EXPIRE_MINUTES: '${ACCESS_TOKEN_EXPIRE_MINUTES:-30}'
      ADMIN_EMAIL: '${ADMIN_EMAIL:-admin@example.com}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD:-adminpassword}'
      ADMIN_FULL_NAME: '${ADMIN_FULL_NAME:-Admin}'
    depends_on:
      - db
    ports:
      - '8000:8000'
    networks:
      - backend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '80:80'
    networks:
      - backend

networks:
  backend:
    driver: bridge
