services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - '5432:5432'
    networks:
      - backend

  backend:
    build: ./backend
    container_name: backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - db
    ports:
      - '8000:8000'
    networks:
      - backend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '80:80'
    networks:
      - backend

networks:
  backend:
    driver: bridge
